# Kafka Configuration
kafka.bootstrap.servers=localhost:9092
kafka.topic=sensor-readings
kafka.group.id=flink-consumer-group-v3

# Cassandra Configuration
cassandra.host=127.0.0.1
cassandra.port=9042
